face_classification:
  id: 001
  dir: face_classification
  image:
    name: face-classification
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 0
  dataset:
    -  { name: "face-class", size: 2, cmd: "tar -xzvf face-class.tar.gz"}
  model:
    name: "情感分析"
    description: "可对人物面部情感进行提取和分析，适用于情感分类等场景"
    size: 1
    nodeport: 32600
  code:
    name: "face_classification"
    description: "情绪检测算法"
    size: 1
    hyperparameter:
      dataset: "/root/dataset/face-class"
      epoch: 1
      batch_size: 32
mtcnn:
  id: 002
  dir: tensorflow-MTCNN
  image:
    name: tensorflow-mtcnn
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 0
  dataset:
    -  { name: mtcnn, size: 2, cmd: "tar -xzvf mtcnn-dataset.tar.gz"}
    -  { name: mtcnn-pre, size: 15, cmd: "tar -xzvf mtcnn-resize-dataset.tar.gz"}
  model:
    name: "人脸检测"
    description: "对复杂条件下的静态图片进行人脸检测，可准确识别出图片中的人脸位置"
    size: 1
    nodeport: 32601
  code:
    name: "mtcnn"
    description: "人脸检测算法"
    size: 1
    hyperparameter:
      epoch: 1
      resize_dataset: "/root/dataset/mtcnn-pre"
      batch_size: 384
      lr: 0.001
      dataset: "/root/dataset/mtcnn"
facenet:
  id: 003
  dir: facenet
  image:
    name: facenet
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 1
  dataset:
    -  { name: lfw, size: 1, cmd: "unzip lfw.zip"}
    -  { name: lfw-mtcnnalign, size: 1, cmd: "unzip lfw_mtcnnalign_160.zip"}
    -  { name: casia-maxpy-mtcnnpy, size: 6, cmd: "unzip casia_maxpy_mtcnnpy_182.zip"}
    -  { name: casia-maxpy-clean, size: 2, cmd: "unzip casia_maxpy_clean.zip"}
  model:
    name: "人脸识别"
    description: "利用深度学习技术，识别出图片中的人物身份，可应用于身份验证等场景"
    size: 1
    nodeport: 32602
  code:
    name: "facenet"
    description: "人脸识别算法"
    size: 1
    hyperparameter:
      MAX_NROF_EPOCHS: 1
      LEARNING_RATE: "-1"
      EPOCH_SIZE: 1
      DATASET_PATH: "/root/dataset/casia-maxpy-mtcnnpy/casia_maxpy_mtcnnpy_182/"
      LFW_DATASET_DIR: "/root/dataset/lfw-mtcnnalign/lfw_mtcnnalign_160/"
crnn_chinese_characters_rec:
  id: 004
  dir: crnn_chinese_characters_rec
  image:
    name: crnn-chinese-characters-rec
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 0
  dataset:
    -  { name: crnn-dataset, size: 2, cmd: "tar xf crnn-dataset.tar"}
  model:
    name: "文本识别"
    description: "利用光学字符识别技术，将图片上的文字内容，直接转换为可编辑文本。支持多场景、高精度的文字检测和识别"
    size: 1
    nodeport: 32603
  code:
    name: "crnn_chinese_characters_rec"
    description: "文本识别算法"
    size: 1
    hyperparameter:
      DATASET: "/root/dataset/crnn-dataset"
      LR: 0.0001
      EPOCHS: 1
      BATCH_SIZE: 64
TTS:
  id: 005
  dir: TTS
  image:
    name: tts
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 0
  dataset:
    -  { name: ljspeech, size: 2, cmd: "tar -xjf LJSpeech-1.1-mini.tar.bz2"}
    -  { name: ljspeech-pre, size: 2, cmd: "tar -xjf pre-LJSpeech-1.1-mini.tar.bz2"}
  model:
    name: "语音合成"
    description: "语音合成技术可以将用户输入的文字，转换成流畅自然的语音输出，可应用于各类机器人发声的场景"
    size: 1
    nodeport: 32604
  code:
    name: "tts"
    description: "语音合成算法"
    size: 1
    hyperparameter:
      DATASET_PATH: "/root/dataset/ljspeech-pre/pre-LJSpeech-1.1-mini/"
      EPOCHS: 1
      LR: 0.0001
      BATCH_SIZE: 1
      EVAL_BATCH_SIZE: 1
stackgan:
  id: 006
  dir: stackgan
  image:
    name: stackgan
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 0
  dataset:
    -  { name: flowers, size: 2, cmd: "tar -zxvf flowers.tar.gz"}
  model:
    name: "智能绘制"
    description: "根据文本中描述的内容进行图像绘制，可形象生动的绘制文字所描述的图像内容"
    size: 2
    nodeport: 32605
  code:
    name: "stackGAN"
    description: "图像绘制算法"
    size: 1
    hyperparameter:
      DATASET_PATH: "/root/dataset/flowers"
      BATCH_SIZE: 64
      STAGEI_EPOCH: 100
      STAGEII_EPOCH: 200
mmdetection:
  id: 007
  dir: mmdetection
  image:
    name: mmdetection
    version: 1.0
    cpu: no
    gpu: yes
    distributed: 0
  dataset:
    -  { name: coco, size: 3, cmd: "unzip coco.zip"}
  model:
    name: "多目标检测"
    description: "多目标检测技术可以同时定位图片中的多个物体，适用于多目标同时查找、识别的场景"
    size: 1
    nodeport: 32606
  code:
    name: "mmdetection"
    description: "目标检测算法"
    size: 1
    hyperparameter:
      DATASET_PATH: "/root/dataset/coco"
      LEARNING_RATE: 0.02
      EPOCHS: 12
      BATCH_SIZE: 2
deepspeech:
  id: 008
  dir: deepspeech
  image:
    name: deepspeech
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 0
  dataset:
    -  { name: cv2, size: 5, cmd: "unzip cv2.zip"}
  model:
    name: "语音识别"
    description: "语音识别技术科将语音转写成文字，适用于会务、演讲授课等场景"
    size: 2
    nodeport: 32607
  code:
    name: "deepSpeech"
    description: "语音识别算法"
    size: 1
    hyperparameter:
      DATASET_PATH: "/root/dataset/cv2"
      EPOCHS: 75
      TRAIN_BATCH_SIZE: 1
      LEARNING_RATE: 0.001
ccpd:
  id: 009
  dir: cc_plate_detect
  image:
    name: ccpd
    version: 1.0
    cpu: yes
    gpu: no
    distributed: 0
  dataset:
    -  { name: cp, size: 1, cmd: "tar -zxvf cp.tar.gz"}
  model:
    name: "车牌识别"
    description: "可自动定位车牌区域，准确率高，识别速度快，识别结果稳定"
    size: 1
    nodeport: 32608
  code:
    name: "plate-recognition"
    description: "车牌识别算法"
    size: 1
    hyperparameter:
      DATA_SET: "/root/dataset/cp"
      BATCH_SIZE: 16
      EPOCH: 3
faster_rcnn:
  id: 010
  dir: faster_rcnn_od
  image:
    name: faster-rcnn
    version: 1.0
    cpu: fromgpu
    gpu: yes
    distributed: 0
  dataset:
    -  { name: vocdevkit2007, size: 2, cmd: "tar xf VOCdevkit2007.tar.gz"}
  model:
    name: "动态目标检测"
    description: "可定位并标记图片中的目标，适用于物体分类等场景"
    size: 2
    nodeport: 32609
  code:
    name: "faster-rcnn"
    description: "动态目标检测算法"
    size: 1
    hyperparameter:
      DATASET: "/root/dataset/vocdevkit2007"
      LR: 0.0004
      EPOCHS: 1
mnist:
  id: 011
  dir: mnist
  image:
    name: mnist
    version: 1.0
    cpu: yes
    gpu: yes
    distributed: 0
  dataset:
    -  { name: mnist, size: 1, cmd: "unzip ds-mnist.zip"}
  model:
    name: "数字识别"
    description: "可识别手写数字，适用于手写内容自动化整理等场景"
    size: 1
    nodeport: 32610
  code:
    name: "mnist"
    description: "数字识别算法"
    size: 1
    hyperparameter:
      DATASET_PATH: "/root/dataset/mnist/"
      TRAINING_EPOCH: 1
      BATCH_SIZE: 128
      LEARNING_RATE: 0.001
      DATA_FORMAT: channels_last
